### ISSUE TITLE
Cannot install using abapGit

### ISSUE THREAD

**Issue by nomssi** [SAP2Moose/SAP2Moose#119]
Error: Package Z2MOOSE_TEST_NO_INITIAL_SELECTN exceeds ABAP 30-characters-name limit

**Comment by RainerWinkler** [comment]
Hi Jaques,

I assume that you want to install the development coding of SAP2Moose, when you just use it, is sufficient to add the report z_moose_extractor to your system.

I use Z2MSE as project prefix. With this prefix the package has less than 30 characters.

There is obviously something missed in the documentation how to install the global classes of SAP2Moose. It is possible to enter a main package that is not Z2MSE, when you do this you have to notice:

1. There is a restriction to the length of the main package (I guess you choosed Z2MOOSE as main package?). This has 7 characters, but the limit is 6 characters at least.

There is also a problem with the Unit Tests, see issue https://github.com/SAP2Moose/SAP2Moose/issues/79. There are hard coded references to package names in the test. I have no fix for this in the moment.

We need a change in the documentation, do you have a proposal for this?

Best regards and happy christmas,
Rainer

**Comment by RainerWinkler** [comment]
Hi @nomssi ,
I added now a description how to install using abapGit in the Readme. I hope it is sufficient. I cannot test this easily, as my SAP testsystem has SAP2Moose already installed.
Thanks,
Rainer
