### ISSUE TITLE
Search for all elements of a class

### ISSUE THREAD

**Issue by pki1982** [SAP2Moose/SAP2Moose#122]
Hello, 

I'm new to SAP2MOOSE and I'm trying to extract whole Z Global Class which doesn't have any parent class (no inheritance).
How to properly set input parameters to achieve this ?

If i choose Element Name: Class and Specific Element: ZCL_MAILING i have message: "Enter a parent name for this type of element, in case of methods this is the class"

Thank you
Pawel

**Comment by RainerWinkler** [comment]
Hello Pawel,

To analyze a method and see what the method uses and what is used by the method you can enter:
In the field "Element name" is a value help.  Click in the field and select Class.
"Parent name": Enter the class name
"Specific element": Enter the methos name

I added a screenshoot how this looks like to the Readme in section Documentation. Is this helping you?

Do not hesitate to ask more :-)

Best regards and a nice Sunday evening,
Rainer

**Comment by pki1982** [comment]
Thank you Rainer for your quick response,

I meant to display whole class with all methods and attributes. Not only one method.

Best regards
Pawel

**Comment by RainerWinkler** [comment]
Hi Pawel,

I am currently only selecting whole packages. This works for me as long as the packages do not contain too many elements. This makes sense when Moose2Model is used to display the result.

When you are interested in the usage as it is displayed by the report you may need the option to select a class. Do you need this? I think the effort to implement it should be not too big.

Best regards
Rainer

**Comment by pki1982** [comment]
Hello Rainer,

I'm the developer-beginner. I'm working on "utility-reusable" class and It would be easier for me to maintain dependencies between methods and attributes. Now I have to use this class in program and then visualize this program in SAP2 Moose. Possibility to show class directly would be very useful.
Of course only if you have some spare time (who has it nowadays ... ;-))

Best regards
Pawel

**Comment by RainerWinkler** [comment]
Hi @pki1982 ,
I have now a solution which can be tested. Just copy the updated coding https://github.com/SAP2Moose/SAP2Moose/blob/master/z_moose_extractor.abap to your report.
Please note that there is now also a documentation for the report which you may add to your local report. I explain there also how to analyze a complete class:
https://github.com/SAP2Moose/SAP2Moose/blob/master/z_moose_extractor_documentation.txt
Best Regards,
Rainer

**Comment by RainerWinkler** [comment]
It is recommendet to have a fix to #128 before relying on a correct "down search" for the new functionality. The "standard" where used works correct. But not the "reversed" one, where the used elements are shown.

**Comment by RainerWinkler** [comment]
Hi @pki1982 ,
issue #128 is fixed. Please test the new feature.
Best Regards,
Rainer

**Comment by RainerWinkler** [comment]
Hi @pki1982 ,
did you had time to test already?
As the change is now productive for a long time, I close this ticket.
Best Regards,
Rainer

**Comment by pki1982** [comment]
Actually it's still waiting for a check. Currently I'm not developing but
surely I'll be back ;-)
Thx for a change.

wt., 28 wrz 2021 o 13:44 Rainer Winkler ***@***.***>
napisał(a):
